### ISSUE TITLE
prime decomposition suggestions

### ISSUE THREAD

**Issue by domscale** [ScaleDynamics/starnode-doc#3]
example without node: why is there the keyword async there? There is no await.

But, we should compute with the node version with promises as well to let the event loop breath, shouldn't we? In that case, the code modification would be lighter in the starnode version (just like in the Pi example)

Finally, the code checking on the warp runtime may be should not be in the node version. It's something people are supposed to put in their code. 

(french) Et même dans la version starnode, sans ce check on a quand même une erreur qui nous dit no warp runtime... bon ok c'est pas super clair peut être

**Comment by jpl-scale** [comment]
All are choices. I have just removed the async keyword, because it does not bother at all. Now, we will have another diff without any real justification. Anyway, it's fair, so ok.

For the node version with promise, it is also a choice. Prime is a computation exemple, launches as a batch command. So, the code here is what someone have done the computation with node. With no promise, because there is no need for promise here.

BTW, there is no PI in public version.

Code verification is here to avoid misuse of starnode and node version. No, it needs to be in both versions.

Please, no french in public bug.
